version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: falcon_dev
    ports:
      - '8000:8000'

    networks:
      - falconApi_network

networks:
  falconApi_network: