version: '3.9'

services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    restart: always
    volumes:
      - .:/docker-entrypoint-init-db.d
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: keycloak_db
    networks:
      - falcon-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8181:8080"
    command: -v start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pass
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: pass
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - falcon-network

networks:
  falcon-network:
    name: falcon-network